name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os:
          [
            blacksmith-4vcpu-ubuntu-2404,
            blacksmith-4vcpu-windows-2025,
            blacksmith-6vcpu-macos-latest,
          ]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./bdgm -> target
      - name: Build
        run: cargo build --verbose
        working-directory: ./bdgm
      - name: Run tests
        run: cargo test --verbose
        working-directory: ./bdgm
